version: 2

models:
  - name: growth_metrics_monthly
    description: "Aggregated monthly user lifecycle metrics and KPIs"
    columns:
      - name: activity_month
        description: "Month of activity"
        tests: [not_null]

      - name: new_users
        description: "Count of new users in this month"
        tests: []

      - name: retained_users
        description: "Count of users retained from previous month"
        tests: []

      - name: resurrected_users
        description: "Users returning after being inactive last month"
        tests: []

      - name: churned_users
        description: "Users active in last month but not this month"
        tests: []

      - name: active_users
        description: "Sum of new, retained, resurrected users"
        tests: []

      - name: quick_ratio
        description: "(new + resurrected) / churned"
        tests: []

      - name: retention_rate
        description: "retained / active users from previous month"
        tests: []
