version: 2

models:
  - name: fct_events
    description: "Event-level fact table used for user lifecycle metrics"
    columns:
      - name: event_ts
        description: "Timestamp of the event"
        data_type: timestamp
        tests: [not_null]

      - name: activity_month
        description: "Truncated month from event timestamp"
        data_type: date
        tests: [not_null]

      - name: user_id
        description: "User who performed the event"
        data_type: string
        tests: [not_null]

      - name: event_type
        description: "Type of event"
        data_type: string
        tests: [not_null]

  - name: dim_users
    description: "User dimension table containing first seen timestamp"
    columns:
      - name: user_id
        description: "Unique user ID"
        data_type: string
        tests: [not_null, unique]

      - name: first_seen_ts
        description: "Timestamp of user's first event"
        data_type: timestamp
        tests: [not_null]

      - name: first_seen_date
        description: "First active date (day granularity)"
        data_type: date
        tests: [not_null]

      - name: first_seen_month
        description: "First active month"
        data_type: date
        tests: [not_null]
      
      - name: first_seen_week
        description: "First active week"
        data_type: date
        tests: [not_null]

  - name: user_lifecycle_week
    description: "Assigns lifecycle status to each user for every week"
    columns:
      - name: user_id
        description: "User ID"
        data_type: string
        tests: [not_null]

      - name: activity_week
        description: "The week of analysis"
        data_type: date
        tests: [not_null]

      - name: user_status
        description: "Lifecycle classification: new, retained, resurrected, churned"
        data_type: string
        tests:
          - not_null
          - accepted_values:
              values: ['new', 'retained', 'resurrected', 'churned']

  - name: user_lifecycle_daily
    description: "Assigns lifecycle status to each user for every daily"
    columns:
      - name: user_id
        description: "User ID"
        data_type: string
        tests: [not_null]

      - name: activity_date
        description: "The day of analysis"
        data_type: date
        tests: [not_null]

      - name: user_status
        description: "Lifecycle classification: new, retained, resurrected, churned"
        data_type: string
        tests:
          - not_null
          - accepted_values:
              values: ['new', 'retained', 'resurrected', 'churned']

  - name: user_lifecycle_monthly
    description: "Assigns lifecycle status to each user for every month"
    columns:
      - name: user_id
        description: "User ID"
        data_type: string
        tests: [not_null]

      - name: activity_month
        description: "The month of analysis"
        data_type: date
        tests: [not_null]

      - name: user_status
        description: "Lifecycle classification: new, retained, resurrected, churned"
        data_type: string
        tests:
          - not_null
          - accepted_values:
              values: ['new', 'retained', 'resurrected', 'churned']
